services:
  app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"  # Expose NestJS on localhost:4000
    environment:
      - MONGODB_URL=mongodb://mongo:27017/new-libera      
      - EVENTSTORE_URL=http://eventstore:2113
    depends_on:
      - mongo
      - eventstore
    command: npm run start:dev

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "12345:27017"
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  eventstore:
    image: eventstore/eventstore:latest
    container_name: eventstore
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      # - EVENTSTORE_TCP_PORT=1113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "3000:2113"  # EventStore UI
      - "1113:1113"  # TCP communication
    volumes:
      - eventstore-data:/var/lib/eventstore

volumes:
  mongo-data:
  eventstore-data:
