version: "3.9"

services:
  app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000" # Expose app on http://localhost:4000
    environment:
      - MONGODB_URL=mongodb://mongo:27017/new-libera
      - EVENTSTORE_URL=http://eventstore:2113
    volumes:
      - ./src:/var/www/src
      - ./tsconfig.json:/var/www/tsconfig.json
      - ./package.json:/var/www/package.json
      - ./package-lock.json:/var/www/package-lock.json
      - /var/www/node_modules
    depends_on:
      - mongo
      - eventstore

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "12345:27017" # Expose MongoDB on http://localhost:12345
    volumes:
      - mongo-data:/data/db

  eventstore:
    image: eventstore/eventstore:latest
    container_name: eventstore
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"  # Web UI and HTTP API at http://localhost:3001
      - "1113:1113"  # TCP port for internal EventStore communication
    volumes:
      - eventstore-data:/var/lib/eventstore

volumes:
  mongo-data:
  eventstore-data:
